# Logiciels requis pour utiliser et travailler sur les documents du cours Info 111
# "gitlab+https://gitlab.u-psud.fr/ter-graphupsud/algorithme_des_plus-courts_chemins_en_cpp/tree/master/projetTER"
name: ter-jupyter

channels:
- conda-forge

dependencies:
- xeus-cling
- notebook
- xwidgets
- ipywidgets
- rise
- bqplot
- pip
- cppyy
- jupyter_contrib_nbextensions
- pip:
    - nbdime
#    - .
